In [36]:
import sys
import os
import pandas as pd
import numpy as np
from programs.links_aansluiting import links_vectortree_aansluiting as lva

stdout = sys.stdout
reload(sys)
sys.setdefaultencoding('latin-1')
sys.stdout = stdout
print os.getcwd()

E:\Projects\Bachelorscriptie

In [43]:
links_certificaten = pd.read_csv('datafiles/dataframes/working/links_certificates.csv', sep='|', header=0)
koppeltabel = pd.read_csv('datafiles/output/working/koppeltabel.csv', sep=';', names=['id_registration', 'certificate_id'])
marijn_zeeland = pd.read_csv('datafiles/dataframes/working/marijn_marriage_zeeland.csv', sep='|', header=0)
links_locaties = pd.read_csv('datafiles/links/locations_v3.csv', sep=';', header=0)

In [44]:
links_locaties

,location_no,location,municipality,province,region,country,lat,lon
0,4,Aagtekerke,Aagtekerke,Zeeland,NaN,Nederland,51.54663,3.51091
1,5,Aalburg,Aalburg,Noord-Brabant,NaN,Nederland,NaN,NaN
2,7,Aalsmeer,Aalsmeer,Noord-Holland,NaN,Nederland,NaN,NaN
3,10,Brakel,Brakel,Gelderland,NaN,Nederland,NaN,NaN
4,12,Aalst,Aalst (NB),Noord-Brabant,NaN,Nederland,NaN,NaN
5,14,Aalsum,Oostdongeradeel,Friesland,NaN,Nederland,NaN,NaN
6,15,Aalten,Aalten,Gelderland,NaN,Nederland,NaN,NaN
7,16,Aalter,NaN,NaN,Gent,België,NaN,NaN
8,17,Aardenburg,Aardenburg,Zeeland,NaN,Nederland,51.27393,3.44536
9,18,Aardswoud,Hoogwoud,Noord-Holland,NaN,Nederland,NaN,NaN
10,19,Aarlanderveen,Aarlanderveen,Zuid-Holland,NaN,Nederland,NaN,NaN
11,20,Aarle-Rixtel,Aarle-Rixtel,Noord-Brabant,NaN,Nederland,NaN,NaN
12,21,Aarschot,NaN,NaN,NaN,België,NaN,NaN
13,25,Abbekerk,Abbekerk,Noord-Holland,NaN,Nederland,NaN,NaN
14,26,Abbenbroek,Abbenbroek,Zuid-Holland,NaN,Nederland,NaN,NaN
15,27,Abcoude,Abcoude,Utrecht,NaN,Nederland,NaN,NaN
16,28,Abcoude-Baambrugge,Abcoude-Baambrugge,Utrecht,NaN,Nederland,NaN,NaN
17,29,Abcoude-Proostdij,Abcoude-Proostdij,Utrecht,NaN,Nederland,NaN,NaN
18,37,Achtkarspelen,Achtkarspelen,Friesland,NaN,Nederland,NaN,NaN
19,39,Achttienhoven,Achttienhoven (UT),Utrecht,NaN,Nederland,NaN,NaN
20,43,Adegem,NaN,NaN,NaN,België,NaN,NaN
21,44,Adinkerke,NaN,NaN,NaN,België,NaN,NaN
22,48,Adorp,Adorp,Groningen,NaN,Nederland,NaN,NaN
23,49,Aduard,Aduard,Groningen,NaN,Nederland,NaN,NaN
24,51,Aengwirden,Aengwirden,Friesland,NaN,Nederland,NaN,NaN
25,55,Ahaus,NaN,NaN,NaN,Duitsland,NaN,NaN
26,56,Aachen,NaN,NaN,NaN,Duitsland,NaN,NaN
27,57,Aachen,NaN,NaN,NaN,Pruissen,NaN,NaN
28,58,Akersloot,Akersloot,Noord-Holland,NaN,Nederland,NaN,NaN
29,59,Akkerwoude,Dantumadeel,Friesland,NaN,Nederland,NaN,NaN
...,...,...,...,...,...,...,...,...
2426,9622,Westenschouwen,Westerschouwen,Zeeland,NaN,Nederland,51.67770,3.71350
2427,9671,Waerschoot,NaN,NaN,NaN,België,NaN,NaN
2428,9672,Waasmunster,NaN,NaN,NaN,België,NaN,NaN
2429,9712,Weseke,NaN,NaN,NaN,Duitsland,NaN,NaN
2430,9805,Woerden,Woerden (UT),Utrecht,NaN,Nederland,NaN,NaN
2431,9856,Zulthe,Roden,Drenthe,NaN,Nederland,NaN,NaN
2432,9860,Zwake,Zwake,Zeeland,NaN,Nederland,51.45777,3.89916
2433,9881,Alphen,Alphen en Riel,Noord-Brabant,NaN,Nederland,NaN,NaN
2434,9884,Buren,Buren,Gelderland,NaN,Nederland,NaN,NaN
2435,9886,Epe,Epe,Gelderland,NaN,Nederland,NaN,NaN
2436,9889,Laren,Laren (NH),Noord-Holland,NaN,Nederland,NaN,NaN
2437,9890,Middelburg,Middelburg (Ze),Zeeland,NaN,Nederland,51.50145,3.61490
2438,9891,Oosterhout,Oosterhout,Noord-Brabant,NaN,Nederland,NaN,NaN
2439,9892,Unknown,Unknown,Unknown,NaN,Unknown,NaN,NaN
2440,9895,Horst,Horst,Limburg,NaN,Nederland,NaN,NaN
2441,9902,Beers,Beers,Noord-Brabant,NaN,Nederland,NaN,NaN
2442,9914,'s-Grevelduin-Capelle,Capelle,Noord-Brabant,NaN,Nederland,NaN,NaN
2443,9922,Unknown,Unknown,Unknown,NaN,Unknown,NaN,NaN
2444,9927,Millingen,Millingen,Gelderland,NaN,Nederland,NaN,NaN
2445,9952,Stein,Stein (LI),Limburg,NaN,Nederland,NaN,NaN
2446,9959,Bergen,Bergen (NH),Noord-Holland,NaN,Nederland,NaN,NaN
2447,9960,Willemsoord,Steenwijkerwold,Overijssel,NaN,Nederland,NaN,NaN
2448,9988,Kalk,NaN,NaN,NaN,Duitsland,NaN,NaN
2449,9992,Zundert en Wernhout,Zundert,Noord-Brabant,NaN,Nederland,NaN,NaN
2450,9994,Unknown,NaN,NaN,Bohemen,Tsjechië,NaN,NaN
2451,9995,Zevenhuizen,Zevenhuizen,Zuid-Holland,NaN,Nederland,NaN,NaN
2452,9998,Essen,NaN,NaN,NaN,België,NaN,NaN
2453,10004,Unknown,Unknown,Unknown,NaN,Unknown,NaN,NaN
2454,10006,Unknown,Unknown,Unknown,NaN,Unknown,NaN,NaN
2455,10010,Not yet standardized,Not yet standardized,Not yet standardized,NaN,Not yet standardized,NaN,NaN

In [39]:
links_certificaten

,certificate_id,certificate_type_num,archive_id,certificate_type_text,date,sequence_no,province,municipality,lat,lon,...,mother_groom_patronym,mother_groom_first_names,father_bride_last_name,father_bride_prefix,father_bride_patronym,father_bride_first_names,mother_bride_last_name,mother_bride_prefix,mother_bride_patronym,mother_bride_first_names
0,698558,2,NaN,NaN,09-06-1801,15,Zeeland,Zaamslag,NaN,NaN,...,NaN,johanna,huijssen,NaN,NaN,cornelis,gouwe,van der,NaN,elizabeth
1,698565,2,NaN,NaN,17-05-1861,8,Zeeland,Zaamslag,NaN,NaN,...,NaN,pieternella,hamer,den,NaN,cornelis,wege,van de,NaN,janneke
2,698612,2,NaN,NaN,01-08-1878,13,Zeeland,Zaamslag,NaN,NaN,...,NaN,janna,pooter,de,NaN,michiel,oppeneer,NaN,NaN,pieternella
3,698616,2,NaN,NaN,19-12-1901,27,Zeeland,Zaamslag,NaN,NaN,...,NaN,cornelia,bokx,de,NaN,gilles,dieleman,NaN,NaN,adriana
4,698644,2,NaN,NaN,25-06-1836,7,Zeeland,Zaamslag,NaN,NaN,...,NaN,adriana,doorn,van,NaN,jan,dronkers,NaN,NaN,pieternella
5,698700,2,NaN,NaN,05-02-1914,1,Zeeland,Zaamslag,NaN,NaN,...,NaN,maria,schoonakker,NaN,NaN,jacobus,verpoorte,NaN,NaN,elizabeth
6,698743,2,NaN,NaN,12-04-1932,1,Zeeland,Zaamslag,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,698762,2,NaN,NaN,22-06-1893,10,Zeeland,Zaamslag,NaN,NaN,...,NaN,suzanna,gerrits,NaN,NaN,andries,bruijne,de,NaN,tanneke
8,698904,2,NaN,NaN,02-04-1856,6,Zeeland,Zaamslag,NaN,NaN,...,NaN,santina,fouw,de,NaN,jan,deij,NaN,NaN,tannetje
9,699013,2,NaN,NaN,10-05-1846,8,Zeeland,Zaamslag,NaN,NaN,...,NaN,anna,alten,van,NaN,floris,michielsen,NaN,NaN,levina
10,699023,2,NaN,NaN,14-07-1824,6,Zeeland,Zaamslag,NaN,NaN,...,NaN,neeltje,jonge,de,NaN,cornelis,jonge,de,NaN,catrina
11,699073,2,NaN,NaN,28-12-1899,16,Zeeland,Zaamslag,NaN,NaN,...,NaN,maria,bakker,NaN,NaN,pieter,verstraten,NaN,NaN,martina
12,699340,2,NaN,NaN,22-01-1896,1,Zeeland,Zaamslag,NaN,NaN,...,NaN,janneke,kerkvoort,van,NaN,maarten,romeijn,NaN,NaN,catharina
13,699415,2,NaN,NaN,24-04-1913,8,Zeeland,Zaamslag,NaN,NaN,...,NaN,wilhelmina johanna,knijff,NaN,NaN,johannes,alberts,NaN,NaN,gerrigje
14,699445,2,NaN,NaN,28-02-1912,6,Zeeland,Zaamslag,NaN,NaN,...,NaN,barbara,verstraaten,NaN,NaN,augustinus,hamelink,NaN,NaN,elisabeth
15,699451,2,NaN,NaN,17-04-1919,11,Zeeland,Zaamslag,NaN,NaN,...,NaN,cornelia,klaassen,NaN,NaN,cornelis,wisse,NaN,NaN,suzanna
16,699519,2,NaN,NaN,21-07-1913,19,Zeeland,Zaamslag,NaN,NaN,...,NaN,jacomina,maas,NaN,NaN,cornelis,geelhoedt,NaN,NaN,maria
17,699702,2,NaN,NaN,19-09-1850,21,Zeeland,Zaamslag,NaN,NaN,...,NaN,klasina,oppe,NaN,NaN,pieter,smidt,de,NaN,maatje
18,699728,2,NaN,NaN,01-03-1829,2,Zeeland,Zaamslag,NaN,NaN,...,NaN,martha,rouw,NaN,NaN,adriaan,haak,NaN,NaN,francoise
19,699773,2,NaN,NaN,04-05-1860,8,Zeeland,Zaamslag,NaN,NaN,...,NaN,jozina,deij,NaN,NaN,cornelis,drongelen,van,NaN,jacomina
20,699785,2,NaN,NaN,17-10-1872,23,Zeeland,Zaamslag,NaN,NaN,...,NaN,hebrina,willemsen,NaN,NaN,cornelis,verpoorte,NaN,NaN,cornelia
21,699942,2,NaN,NaN,21-10-1810,18,Zeeland,Zaamslag,NaN,NaN,...,NaN,catrina,hollander,de,NaN,joannis,corebijter,de,NaN,esther
22,699994,2,NaN,NaN,12-09-1830,17,Zeeland,Zaamslag,NaN,NaN,...,NaN,neeltje,hamelink,NaN,NaN,marinus,versluis,NaN,NaN,jozina
23,700167,2,NaN,NaN,29-06-1855,10,Zeeland,Zaamslag,NaN,NaN,...,NaN,dina,demenie,NaN,NaN,jan,verpoorte,NaN,NaN,lidewij
24,700247,2,NaN,NaN,11-02-1858,2,Zeeland,Zaamslag,NaN,NaN,...,NaN,hebrina,krane,NaN,NaN,jacobus,zeeuw,de,NaN,jacoba johanna
25,700265,2,NaN,NaN,07-04-1892,7,Zeeland,Zaamslag,NaN,NaN,...,NaN,jacoba,hamelink,NaN,NaN,jan,nortier,NaN,NaN,maria
26,700277,2,NaN,NaN,03-03-1847,1,Zeeland,Zaamslag,NaN,NaN,...,NaN,cornelia,deurwaarder,den,NaN,gilles,haak,NaN,NaN,cornelia carolina
27,700388,2,NaN,NaN,16-05-1907,5,Zeeland,Zaamslag,NaN,NaN,...,NaN,catharina,goosen,NaN,NaN,abraham,feijter,de,NaN,adriana
28,700428,2,NaN,NaN,08-08-1801,19,Zeeland,Zaamslag,NaN,NaN,...,NaN,willemina,hoofd,van der,NaN,willem,drongelen,van,NaN,elizabeth
29,700431,2,NaN,NaN,17-08-1848,21,Zeeland,Zaamslag,NaN,NaN,...,NaN,helena,riemens,NaN,NaN,guillaam,michielsen,NaN,NaN,suzanna
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193010,891144,2,NaN,NaN,15-03-1811,1,Zeeland,Maire,NaN,NaN,...,NaN,neeltje claasse,leven,van 't,NaN,pieter,stelle,van,NaN,maria
193011,736737,2,NaN,NaN,23-04-1797,8.0,Zeeland,Lamswaarde,NaN,NaN,...,NaN,petronille,rogiers,NaN,NaN,pierre,cambeen,NaN,NaN,barbe
193012,762058,2,NaN,NaN,25-06-1797,9.0,Zeeland,Lamswaarde,NaN,NaN,...,NaN,cecilia,stout,NaN,NaN,cornelis,cammaart,NaN,NaN,marie
193013,773998,2,NaN,NaN,18-12-1796,1.0,Zeeland,Lamswaarde,NaN,NaN,...,NaN,catherine,colsen,NaN,NaN,cornille,hulst,van,NaN,marie anne
193014,777098,2,NaN,NaN,23-04-1797,7.0,Zeeland,Lamswaarde,NaN,NaN,...,NaN,elisabeth,hekelaer,NaN,NaN,francois,willemse,NaN,NaN,appollone
193015,790951,2,NaN,NaN,25-02-1797,5.0,Zeeland,Lamswaarde,NaN,NaN,...,NaN,catherine,luijcks,NaN,NaN,pierre,buijs,NaN,NaN,susanne
193016,816581,2,NaN,NaN,24-01-1797,3.0,Zeeland,Lamswaarde,NaN,NaN,...,NaN,appolone,compiet,NaN,NaN,francois,dorsselaer,van,NaN,andrisine
193017,822947,2,NaN,NaN,19-02-1797,4.0,Zeeland,Lamswaarde,NaN,NaN,...,NaN,joanne,laer,van,NaN,jacques,luijkx,NaN,NaN,joanne
193018,854834,2,NaN,NaN,17-09-1797,12,Zeeland,Lamswaarde,NaN,NaN,...,NaN,joanna,annaart,NaN,NaN,pierre,weesepoel,NaN,NaN,joanne
193019,854870,2,NaN,NaN,09-07-1797,10,Zeeland,Lamswaarde,NaN,NaN,...,NaN,cornelia,walle,van der,NaN,jean,bruijn,de,NaN,elisabeth
193020,855085,2,NaN,NaN,22-01-1797,2,Zeeland,Lamswaarde,NaN,NaN,...,NaN,catherine,daris,NaN,NaN,jean,dorsselaer,van,NaN,anna
193021,866771,2,NaN,NaN,05-03-1797,6,Zeeland,Lamswaarde,NaN,NaN,...,NaN,marie,pieters,NaN,NaN,pierre,aertsen,NaN,NaN,jeanne
193022,889265,2,NaN,NaN,21-07-1797,11,Zeeland,Lamswaarde,NaN,NaN,...,NaN,marie joanne,cappaart,NaN,NaN,jean,tiggelen,van,NaN,eelena
193023,770819,2,NaN,NaN,17-01-1812,1.0,Zeeland,Rengerskerke,NaN,NaN,...,NaN,aaltje willemse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193024,800239,2,NaN,NaN,18-09-1811,2.0,Zeeland,Rengerskerke,NaN,NaN,...,NaN,NaN,evertsen,NaN,NaN,paulus,NaN,NaN,NaN,NaN
193025,811824,2,NaN,NaN,19-08-1811,1.0,Zeeland,Rengerskerke,NaN,NaN,...,NaN,maria,wetsteen,NaN,NaN,corneille,cars,NaN,NaN,leuntje
193026,784536,2,NaN,NaN,22-12-1814,1.0,Zeeland,Valkenisse (Walcheren),NaN,NaN,...,NaN,adriana,weststrate,NaN,NaN,christiaan matthijse,potters,NaN,NaN,willemina
193027,879001,2,NaN,NaN,14-02-1811,1,Zeeland,Valkenisse (Walcheren),NaN,NaN,...,NaN,johanna,kampen,van,NaN,hendrik,hameling,NaN,NaN,adriana
193028,880591,2,NaN,NaN,25-06-1812,1,Zeeland,Valkenisse (Walcheren),NaN,NaN,...,NaN,jacomina,blok,NaN,NaN,ariaan,weststrate,NaN,NaN,janna christiaanse
193029,798895,2,NaN,NaN,18-05-1814,1.0,Zeeland,'s-Gravenhoek,NaN,NaN,...,NaN,janna,huiszoon,NaN,NaN,machiel,lievense,NaN,NaN,tannetje
193030,801054,2,NaN,NaN,29-04-1813,1.0,Zeeland,'s-Gravenhoek,NaN,NaN,...,NaN,janna,koster,NaN,NaN,cornelus willemse,gilst,van,NaN,cornelia
193031,827937,2,NaN,NaN,06-10-1811,1.0,Zeeland,'s-Gravenhoek,NaN,NaN,...,NaN,lena cornelisse,huijsson,NaN,NaN,machiel,lievense,NaN,NaN,tanne
193032,823370,2,NaN,NaN,17-07-1811,1.0,Zeeland,Nieuw-Strijen,NaN,NaN,...,NaN,lena,poot,NaN,NaN,janus,lindhout,NaN,NaN,neeltje
193033,856413,2,NaN,NaN,07-09-1812,1,Zeeland,Zwake,NaN,NaN,...,NaN,maria,waaij,de,NaN,jan,jonge,de,NaN,janna
193034,873159,2,NaN,NaN,22-05-1815,1,Zeeland,Zwake,NaN,NaN,...,NaN,maria,waaij,de,NaN,jan,jonge,de,NaN,johanna
193035,866558,2,NaN,NaN,02-06-1937,45,NaN,Wilrijk,NaN,NaN,...,NaN,maria johanna,saffel,de,NaN,franciscus,megroot,NaN,NaN,clementia
193036,880865,2,NaN,NaN,02-06-1814,1,Zeeland,Hoogelande,NaN,NaN,...,NaN,adriaana,joram,NaN,NaN,johan,kerhove,NaN,NaN,johanna
193037,884021,2,NaN,NaN,23-12-1813,1,Zeeland,Hoogelande,NaN,NaN,...,NaN,maatje,vlaanderen,van,NaN,pieter franse,bommelje,NaN,NaN,prina
193038,888940,2,NaN,NaN,23-06-1814,2,Zeeland,Hoogelande,NaN,NaN,...,NaN,janna,kraaije,NaN,NaN,jacobus,flissebaalje,NaN,NaN,adriana
193039,891354,2,NaN,NaN,25-04-1936,51,NaN,Gent,NaN,NaN,...,NaN,aafje,dost,NaN,NaN,johann,dost,NaN,NaN,karolina emma

In [40]:
koppeltabel

        id_registration  certificate_id
0                698558         1859581
1                698565         1858880
2                698612         1860206
3                698616         1858923
4                698644         1858529
5                698700         1858816
6                698762         1858557
7                698904         1859455
8                699013         1858037
9                699023         1859464
10               699073         1858619
11               699340         1860488
12               699415         1860382
13               699445         1860373
14               699451         1859247
15               699519         1859888
16               699702         1859165
17               699728         1858060
18               699773         1859029
19               699785         1858809
20               699942         1860281
21               699994         1859343
22               700167         1859899
23               700247         1859881
24               700265         1858989
25               700277         1860389
26               700388         1858768
27               700428         1859737
28               700431         1859676
29               700591         1857921
...                 ...             ...
163009           806491         1916324
163010           834935         1916320
163011           836215         1916326
163012           874219         1916322
163013           735582         1734822
163014           832286         1734820
163015           891144         1734825
163016           736737         1734786
163017           762058         1734791
163018           773998         1734788
163019           777098         1734797
163020           790951         1734795
163021           816581         1734811
163022           822947         1734804
163023           854834         1734806
163024           854870         1734793
163025           855085         1734800
163026           866771         1734802
163027           889265         1734808
163028           770819         1805671
163029           800239         1805669
163030           811824         1805673
163031           801054         1661112
163032           827937         1661108
163033           823370         1774143
163034           856413         1869652
163035           873159         1869653
163036           880865         1678573
163037           884021         1678575
163038           888940         1678577

[163039 rows x 2 columns]

In [41]:
marijn_zeeland

,certificate_id,certificate_type_num,archive_id,certificate_type_text,date,sequence_no,province,municipality,lat,lon,...,mother_groom_patronym,mother_groom_first_names,father_bride_last_name,father_bride_prefix,father_bride_patronym,father_bride_first_names,mother_bride_last_name,mother_bride_prefix,mother_bride_patronym,mother_bride_first_names
0,1557526,2,19,Huwelijksakte,23-06-1821,5,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Jongepier,NaN,NaN,Anthony,Poppe,NaN,NaN,Catharina
1,1557529,2,19,Echtscheidingsakte,06-01-1897,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1557532,2,19,Huwelijksakte,31-08-1892,3,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Maljers,NaN,NaN,Cornelis,Plaa,de,NaN,Maatje
3,1557536,2,19,Huwelijksakte,05-05-1915,2,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Katharina,Visser,de,NaN,Pieter,Dekker,NaN,NaN,Elizabeth
4,1557539,2,19,Huwelijksakte,20-12-1823,4,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Caljouw,NaN,NaN,Wouter,Hendrikse,NaN,NaN,Tannetje
5,1557543,2,19,Huwelijksakte,19-05-1920,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Broeke,van den,NaN,Marinus,Krijger,NaN,NaN,Pieternella
6,1557546,2,19,Huwelijksakte,08-10-1919,6,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Maljers,NaN,NaN,Floris,Krijger,NaN,NaN,Cornelia
7,1557549,2,19,Huwelijksakte,09-05-1890,2,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Pieternella,Voogd,de,NaN,Willem,Sturm,NaN,NaN,Leintje
8,1557552,2,19,Huwelijksakte,06-10-1922,3,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Kerkhove,NaN,NaN,Cornelis,Jobse,NaN,NaN,Maria
9,1557555,2,19,Huwelijksakte,11-07-1845,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Elizabeth,Broeke,van den,NaN,Cornelis Joosse,Rijke,de,NaN,Maria Janse
10,1557558,2,19,Huwelijksakte,16-01-1836,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Janna,Bosselaar,NaN,NaN,Jan,Boogaart,NaN,NaN,Maria
11,1557561,2,19,Huwelijksakte,10-05-1820,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Wilhelmina,Lous,NaN,NaN,Lourens Jacobse,Permetier,NaN,NaN,Maatje
12,1557564,2,19,Huwelijksakte,07-05-1880,2,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Willemina,Schout,NaN,NaN,Lourus,Vos,NaN,NaN,Prina
13,1557567,2,19,Huwelijksakte,19-06-1912,3,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Willemina,Adriaanse,NaN,NaN,Adam,Marinissen,NaN,NaN,Catharina
14,1557570,2,19,Huwelijksakte,29-03-1905,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Hollander,den,NaN,Cornelis,Dingemanse,NaN,NaN,Pieternella
15,1557573,2,19,Huwelijksakte,10-05-1907,5,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Hollander,den,NaN,Cornelis,Dingemanse,NaN,NaN,Pieternella
16,1557576,2,19,Huwelijksakte,13-04-1921,3,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Pieternella,Minderhoud,NaN,NaN,Johannes,Lange,de,NaN,Johanna Maria
17,1557580,2,19,Huwelijksakte,04-05-1904,2,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Cornelia,Wisse,NaN,NaN,Simon,Corr?,NaN,NaN,Neeltje
18,1557584,2,19,Huwelijksakte,16-03-1814,2,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Pietronella Marinusse,Slus,NaN,NaN,Hendrik Pieterse,Arenoudse,NaN,NaN,Janna Janse
19,1557587,2,19,Huwelijksakte,12-06-1891,4,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Jacomina,Dingemanse,NaN,NaN,Lein,Keulen,van,NaN,Maria
20,1557590,2,19,Huwelijksakte,27-02-1874,2,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Willemina,Arendse,NaN,NaN,Pieter Jacobus,Coppoolse,NaN,NaN,Maria
21,1557593,2,19,Huwelijksakte,15-12-1915,5,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Pieternella,Weele,van der,NaN,Andries,Caboord,NaN,NaN,Jacoba
22,1557596,2,19,Huwelijksakte,22-10-1817,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Leuntje Claassen,Kleijnepier,NaN,NaN,Willem,Voogd,de,NaN,Leuntje
23,1557599,2,19,Huwelijksakte,15-11-1912,4,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Willemina,Maljers,NaN,NaN,Floris,Minderhoud,NaN,NaN,Adriana
24,1557602,2,19,Huwelijksakte,01-03-1907,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Sinke,NaN,NaN,Pieter,Klaase,NaN,NaN,Jacoba
25,1557605,2,19,Huwelijksakte,29-09-1860,5,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Cornelia,Dommisse,NaN,NaN,Adriaan,Bos,NaN,NaN,Leintje
26,1557608,2,19,Huwelijksakte,09-05-1917,1,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Sinke,NaN,NaN,Pieter,Klaassen,NaN,NaN,Jacoba
27,1557612,2,19,Huwelijksakte,10-05-1907,4,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Willemina,Labruij?re,NaN,NaN,Adriaan,Maas,NaN,NaN,Jannetje
28,1557615,2,19,Huwelijksakte,08-12-1843,6,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Maria,Wisse,NaN,NaN,Simon,Coppoolse,NaN,NaN,Neeltje
29,1557618,2,19,Huwelijksakte,08-08-1873,6,Zeeland,Aagtekerke,51.54663,3.51091,...,NaN,Johanna,Sturm,NaN,NaN,Jacob,Kesteloo,NaN,NaN,Catharina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164728,1937521,2,19,Huwelijksakte,20-08-1886,12,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Aagje,NaN,NaN,NaN,NaN,Jeroense,NaN,NaN,Maria
164729,1937525,2,19,Huwelijksakte,18-04-1902,9,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Maria Janna,Goedegebuure,NaN,NaN,Iman,Vroegop,NaN,NaN,Adriana
164730,1937530,2,19,Huwelijksakte,04-09-1891,14,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Cornelia,Hage,NaN,NaN,Jan,Hage,NaN,NaN,Maatje
164731,1937534,2,19,Huwelijksakte,16-05-1890,11,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Cornelia,Vermaas,NaN,NaN,Jacobus,Werf,van der,NaN,Cornelia
164732,1937540,2,19,Huwelijksakte,13-03-1857,6,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Haagje,Vogelenzang,NaN,NaN,Alexander,Doel,van den,NaN,Janna
164733,1937545,2,19,Huwelijksakte,01-04-1870,5,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Aagje,Joppe,NaN,NaN,Abraham,Giljam,NaN,NaN,Maria
164734,1937549,2,19,Huwelijksakte,02-12-1910,31,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Lientje,Popering,van,NaN,Jacob,Ligtendag,NaN,NaN,Abramina
164735,1937554,2,19,Huwelijksakte,06-05-1887,9,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Cornelia,Fase,NaN,NaN,Pieter,Jonge,de,NaN,Maatje
164736,1937558,2,19,Huwelijksakte,26-05-1865,9,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Aagje,Oosse,NaN,NaN,Simon,Fase,NaN,NaN,Cornelia
164737,1937563,2,19,Huwelijksakte,25-04-1884,8,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Cornelia,Gunst,NaN,NaN,Pieter,Slikke,van der,NaN,Anna
164738,1937568,2,19,Huwelijksakte,11-08-1921,18,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Maria Aberdina,Buijs,NaN,NaN,Adriaan,Goedegebuure,NaN,NaN,Trijntje Adriana
164739,1937572,2,19,Huwelijksakte,16-02-1827,5,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Johanna,Goedegebuure,NaN,NaN,Bartel,Platdijk,NaN,NaN,Dina
164740,1937577,2,19,Huwelijksakte,12-10-1888,16,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Maria Janna,Giljam,NaN,NaN,Hendrik,Stormezand,NaN,NaN,Huberdina
164741,1937581,2,19,Huwelijksakte,14-03-1913,10,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Lientje,Slootmaker,NaN,NaN,Jacob,Ruijter,de,NaN,Lena
164742,1937587,2,19,Huwelijksakte,21-05-1858,12,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Haagje,Haan,den,NaN,Jacob,Klooster,van der,NaN,Adriaantje
164743,1937591,2,19,Huwelijksakte,01-04-1910,8,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Lientje,Ridderhof,NaN,NaN,Josias,Noordijke,NaN,NaN,Adriaantje Cornelia
164744,1937596,2,19,Huwelijksakte,28-04-1920,11,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Maria Aberdina,Engelsman,den,NaN,Jacob,Laban,NaN,NaN,Pieternella
164745,1937600,2,19,Huwelijksakte,24-08-1816,5,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Maatje,Vroegop,NaN,NaN,Marinus,Goedegebuure,NaN,NaN,Lientje
164746,1937605,2,19,Huwelijksakte,05-02-1884,3,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Geertrui,Halteren,van,NaN,Jan,Welle,van der,NaN,Janna
164747,1937609,2,19,Huwelijksakte,19-07-1872,11,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Geertruij,Snoep,NaN,NaN,Willem,Douw,NaN,NaN,Jannetje
164748,1937614,2,19,Huwelijksakte,04-08-1911,13,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Jozina,Boogaart,van den,NaN,Gerard,Kaashoek,NaN,NaN,Hendrina
164749,1937619,2,19,Huwelijksakte,24-08-1838,6,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Janna,Quist,NaN,NaN,Pieter,Vermaas,NaN,NaN,Maatje
164750,1937624,2,19,Huwelijksakte,06-05-1898,10,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Dina,Vroegop,NaN,NaN,Willem,Duijser,NaN,NaN,Johanna
164751,1937628,2,19,Huwelijksakte,13-10-1922,20,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Adriana,Goedegebuure,NaN,NaN,Jan,Quist,NaN,NaN,Maartje
164752,1937633,2,19,Huwelijksakte,10-03-1814,4,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Sara,Malipart,NaN,NaN,Jan,Manisse,NaN,NaN,Neeltje
164753,1937638,2,19,Huwelijksakte,27-05-1859,7,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Cornelia,Haze,NaN,NaN,Domus,Beke,NaN,NaN,Cornelia
164754,1937642,2,19,Huwelijksakte,19-05-1841,9,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Pieternella,Bogaart,van den,NaN,Abraham,Vroegop,NaN,NaN,Janna
164755,1937646,2,19,Huwelijksakte,25-08-1837,12,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Sara,Overbeeke,NaN,NaN,Iman,Schouwen,van,NaN,Josina
164756,1937651,2,19,Huwelijksakte,04-01-1884,1,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Victoire,Klooster,van der,NaN,Marcus,Leune,NaN,NaN,Jannetje
164757,1937656,2,19,Huwelijksakte,07-06-1861,8,Zeeland,Sint Annaland,51.59977,4.10187,...,NaN,Hendrika,Goudzwaard,NaN,NaN,Jan,Overbeeke,NaN,NaN,Adriana

In [53]:
links_certificaten['lat'] = links_certificaten['municipality'].map(links_locaties[['location', 'lat']].set_index('location').to_dict()['lat'])

In [55]:
links_certificaten['lon'] = links_certificaten['municipality'].map(links_locaties[['location', 'lon']].set_index('location').to_dict()['lon'])

In [56]:
links_certificaten

,certificate_id,certificate_type_num,archive_id,certificate_type_text,date,sequence_no,province,municipality,lat,lon,...,mother_groom_patronym,mother_groom_first_names,father_bride_last_name,father_bride_prefix,father_bride_patronym,father_bride_first_names,mother_bride_last_name,mother_bride_prefix,mother_bride_patronym,mother_bride_first_names
0,698558,2,NaN,NaN,09-06-1801,15,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,johanna,huijssen,NaN,NaN,cornelis,gouwe,van der,NaN,elizabeth
1,698565,2,NaN,NaN,17-05-1861,8,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,pieternella,hamer,den,NaN,cornelis,wege,van de,NaN,janneke
2,698612,2,NaN,NaN,01-08-1878,13,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,janna,pooter,de,NaN,michiel,oppeneer,NaN,NaN,pieternella
3,698616,2,NaN,NaN,19-12-1901,27,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,cornelia,bokx,de,NaN,gilles,dieleman,NaN,NaN,adriana
4,698644,2,NaN,NaN,25-06-1836,7,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,adriana,doorn,van,NaN,jan,dronkers,NaN,NaN,pieternella
5,698700,2,NaN,NaN,05-02-1914,1,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,maria,schoonakker,NaN,NaN,jacobus,verpoorte,NaN,NaN,elizabeth
6,698743,2,NaN,NaN,12-04-1932,1,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,698762,2,NaN,NaN,22-06-1893,10,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,suzanna,gerrits,NaN,NaN,andries,bruijne,de,NaN,tanneke
8,698904,2,NaN,NaN,02-04-1856,6,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,santina,fouw,de,NaN,jan,deij,NaN,NaN,tannetje
9,699013,2,NaN,NaN,10-05-1846,8,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,anna,alten,van,NaN,floris,michielsen,NaN,NaN,levina
10,699023,2,NaN,NaN,14-07-1824,6,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,neeltje,jonge,de,NaN,cornelis,jonge,de,NaN,catrina
11,699073,2,NaN,NaN,28-12-1899,16,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,maria,bakker,NaN,NaN,pieter,verstraten,NaN,NaN,martina
12,699340,2,NaN,NaN,22-01-1896,1,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,janneke,kerkvoort,van,NaN,maarten,romeijn,NaN,NaN,catharina
13,699415,2,NaN,NaN,24-04-1913,8,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,wilhelmina johanna,knijff,NaN,NaN,johannes,alberts,NaN,NaN,gerrigje
14,699445,2,NaN,NaN,28-02-1912,6,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,barbara,verstraaten,NaN,NaN,augustinus,hamelink,NaN,NaN,elisabeth
15,699451,2,NaN,NaN,17-04-1919,11,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,cornelia,klaassen,NaN,NaN,cornelis,wisse,NaN,NaN,suzanna
16,699519,2,NaN,NaN,21-07-1913,19,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,jacomina,maas,NaN,NaN,cornelis,geelhoedt,NaN,NaN,maria
17,699702,2,NaN,NaN,19-09-1850,21,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,klasina,oppe,NaN,NaN,pieter,smidt,de,NaN,maatje
18,699728,2,NaN,NaN,01-03-1829,2,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,martha,rouw,NaN,NaN,adriaan,haak,NaN,NaN,francoise
19,699773,2,NaN,NaN,04-05-1860,8,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,jozina,deij,NaN,NaN,cornelis,drongelen,van,NaN,jacomina
20,699785,2,NaN,NaN,17-10-1872,23,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,hebrina,willemsen,NaN,NaN,cornelis,verpoorte,NaN,NaN,cornelia
21,699942,2,NaN,NaN,21-10-1810,18,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,catrina,hollander,de,NaN,joannis,corebijter,de,NaN,esther
22,699994,2,NaN,NaN,12-09-1830,17,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,neeltje,hamelink,NaN,NaN,marinus,versluis,NaN,NaN,jozina
23,700167,2,NaN,NaN,29-06-1855,10,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,dina,demenie,NaN,NaN,jan,verpoorte,NaN,NaN,lidewij
24,700247,2,NaN,NaN,11-02-1858,2,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,hebrina,krane,NaN,NaN,jacobus,zeeuw,de,NaN,jacoba johanna
25,700265,2,NaN,NaN,07-04-1892,7,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,jacoba,hamelink,NaN,NaN,jan,nortier,NaN,NaN,maria
26,700277,2,NaN,NaN,03-03-1847,1,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,cornelia,deurwaarder,den,NaN,gilles,haak,NaN,NaN,cornelia carolina
27,700388,2,NaN,NaN,16-05-1907,5,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,catharina,goosen,NaN,NaN,abraham,feijter,de,NaN,adriana
28,700428,2,NaN,NaN,08-08-1801,19,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,willemina,hoofd,van der,NaN,willem,drongelen,van,NaN,elizabeth
29,700431,2,NaN,NaN,17-08-1848,21,Zeeland,Zaamslag,51.31274,3.91314,...,NaN,helena,riemens,NaN,NaN,guillaam,michielsen,NaN,NaN,suzanna
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193010,891144,2,NaN,NaN,15-03-1811,1,Zeeland,Maire,51.71507,3.72214,...,NaN,neeltje claasse,leven,van 't,NaN,pieter,stelle,van,NaN,maria
193011,736737,2,NaN,NaN,23-04-1797,8.0,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,petronille,rogiers,NaN,NaN,pierre,cambeen,NaN,NaN,barbe
193012,762058,2,NaN,NaN,25-06-1797,9.0,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,cecilia,stout,NaN,NaN,cornelis,cammaart,NaN,NaN,marie
193013,773998,2,NaN,NaN,18-12-1796,1.0,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,catherine,colsen,NaN,NaN,cornille,hulst,van,NaN,marie anne
193014,777098,2,NaN,NaN,23-04-1797,7.0,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,elisabeth,hekelaer,NaN,NaN,francois,willemse,NaN,NaN,appollone
193015,790951,2,NaN,NaN,25-02-1797,5.0,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,catherine,luijcks,NaN,NaN,pierre,buijs,NaN,NaN,susanne
193016,816581,2,NaN,NaN,24-01-1797,3.0,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,appolone,compiet,NaN,NaN,francois,dorsselaer,van,NaN,andrisine
193017,822947,2,NaN,NaN,19-02-1797,4.0,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,joanne,laer,van,NaN,jacques,luijkx,NaN,NaN,joanne
193018,854834,2,NaN,NaN,17-09-1797,12,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,joanna,annaart,NaN,NaN,pierre,weesepoel,NaN,NaN,joanne
193019,854870,2,NaN,NaN,09-07-1797,10,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,cornelia,walle,van der,NaN,jean,bruijn,de,NaN,elisabeth
193020,855085,2,NaN,NaN,22-01-1797,2,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,catherine,daris,NaN,NaN,jean,dorsselaer,van,NaN,anna
193021,866771,2,NaN,NaN,05-03-1797,6,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,marie,pieters,NaN,NaN,pierre,aertsen,NaN,NaN,jeanne
193022,889265,2,NaN,NaN,21-07-1797,11,Zeeland,Lamswaarde,51.33000,4.05000,...,NaN,marie joanne,cappaart,NaN,NaN,jean,tiggelen,van,NaN,eelena
193023,770819,2,NaN,NaN,17-01-1812,1.0,Zeeland,Rengerskerke,51.66917,3.86944,...,NaN,aaltje willemse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193024,800239,2,NaN,NaN,18-09-1811,2.0,Zeeland,Rengerskerke,51.66917,3.86944,...,NaN,NaN,evertsen,NaN,NaN,paulus,NaN,NaN,NaN,NaN
193025,811824,2,NaN,NaN,19-08-1811,1.0,Zeeland,Rengerskerke,51.66917,3.86944,...,NaN,maria,wetsteen,NaN,NaN,corneille,cars,NaN,NaN,leuntje
193026,784536,2,NaN,NaN,22-12-1814,1.0,Zeeland,Valkenisse (Walcheren),NaN,NaN,...,NaN,adriana,weststrate,NaN,NaN,christiaan matthijse,potters,NaN,NaN,willemina
193027,879001,2,NaN,NaN,14-02-1811,1,Zeeland,Valkenisse (Walcheren),NaN,NaN,...,NaN,johanna,kampen,van,NaN,hendrik,hameling,NaN,NaN,adriana
193028,880591,2,NaN,NaN,25-06-1812,1,Zeeland,Valkenisse (Walcheren),NaN,NaN,...,NaN,jacomina,blok,NaN,NaN,ariaan,weststrate,NaN,NaN,janna christiaanse
193029,798895,2,NaN,NaN,18-05-1814,1.0,Zeeland,'s-Gravenhoek,NaN,3.77917,...,NaN,janna,huiszoon,NaN,NaN,machiel,lievense,NaN,NaN,tannetje
193030,801054,2,NaN,NaN,29-04-1813,1.0,Zeeland,'s-Gravenhoek,NaN,3.77917,...,NaN,janna,koster,NaN,NaN,cornelus willemse,gilst,van,NaN,cornelia
193031,827937,2,NaN,NaN,06-10-1811,1.0,Zeeland,'s-Gravenhoek,NaN,3.77917,...,NaN,lena cornelisse,huijsson,NaN,NaN,machiel,lievense,NaN,NaN,tanne
193032,823370,2,NaN,NaN,17-07-1811,1.0,Zeeland,Nieuw-Strijen,51.53000,4.13300,...,NaN,lena,poot,NaN,NaN,janus,lindhout,NaN,NaN,neeltje
193033,856413,2,NaN,NaN,07-09-1812,1,Zeeland,Zwake,51.45777,3.89916,...,NaN,maria,waaij,de,NaN,jan,jonge,de,NaN,janna
193034,873159,2,NaN,NaN,22-05-1815,1,Zeeland,Zwake,51.45777,3.89916,...,NaN,maria,waaij,de,NaN,jan,jonge,de,NaN,johanna
193035,866558,2,NaN,NaN,02-06-1937,45,NaN,Wilrijk,NaN,NaN,...,NaN,maria johanna,saffel,de,NaN,franciscus,megroot,NaN,NaN,clementia
193036,880865,2,NaN,NaN,02-06-1814,1,Zeeland,Hoogelande,51.53760,3.80503,...,NaN,adriaana,joram,NaN,NaN,johan,kerhove,NaN,NaN,johanna
193037,884021,2,NaN,NaN,23-12-1813,1,Zeeland,Hoogelande,51.53760,3.80503,...,NaN,maatje,vlaanderen,van,NaN,pieter franse,bommelje,NaN,NaN,prina
193038,888940,2,NaN,NaN,23-06-1814,2,Zeeland,Hoogelande,51.53760,3.80503,...,NaN,janna,kraaije,NaN,NaN,jacobus,flissebaalje,NaN,NaN,adriana
193039,891354,2,NaN,NaN,25-04-1936,51,NaN,Gent,NaN,NaN,...,NaN,aafje,dost,NaN,NaN,johann,dost,NaN,NaN,karolina emma