In [1]:
import os, sys
import pandas as pd
import numpy as np
import mysql.connector

stdout = sys.stdout
reload(sys)
sys.setdefaultencoding('latin-1')
sys.stdout = stdout

In [2]:
conn = mysql.connector.connect(host='localhost', database='links_zeeland', user='root', password='3016BE_17e') 
fathers = pd.read_sql("SELECT id_registration, firstname, familyname FROM persons WHERE registration_maintype = 3 and role = 3", con=conn)
mothers = pd.read_sql('SELECT id_registration, firstname, familyname FROM persons WHERE registration_maintype = 3 and role = 2', con=conn)
conn.close()

In [3]:
merged = fathers.merge(mothers, on='id_registration')
merged.columns = ['id_registration', 'fname_p_m', 'lname_p_m', 'fname_p_f', 'lname_p_f']
merged.fname_p_m = merged.fname_p_m.apply(lambda s: s.split(' ')[0])
merged.fname_p_f = merged.fname_p_f.apply(lambda s: s.split(' ')[0])
merged

        id_registration    fname_p_m     lname_p_m   fname_p_f     lname_p_f
0                892539      lourens    dingemanse     adriana         poppe
1                892540      hendrik  hennebreuker    isabella          reur
2                892541    alexander       pieters    mathilda       koemans
3                892542     josephus         damme    dorothea        bergen
4                892543       pieter          lahr    cornelia       busquet
5                892544    gregorius         vonck        anna       picavet
6                892545
7                892546          jan         klerk       maria           dam
8                892547     johannes       bartman     johanna          lith
9                892548
10               892549      adriaan      schouwen        lena        fondse
11               892550     leendert      verseput       krina         sluis
12               892551          jan     sneevliet     lientje           hem
13               892552      abraham         zeeuw     adriana       schotte
14               892553      laurens    labruijere     johanna       geertse
15               892554        krijn         quaak   catharina         besoo
16               892555
17               892556        louis     aspeslagh     johanna         munck
18               892557      marinus      kerkhove     adriana       jacobse
19               892558      marinus      hamelink      jozina      versluis
20               892559       petrus      huilmand      sophia         baele
21               892560       jasper          hoek       maria     winkelman
22               892561     leendert           bal    apolonia        dienst
23               892562       pieter       heijens   christina         baart
24               892563      abraham         jonge   frederika      gelderen
25               892564      hendrik        desson      jozina           mol
26               892565     johannes       lievens   francisca         velde
27               892566     johannes        linden      helena        koster
28               892567      adriaan       kieboom   catharina  modderkreeke
29               892568     johannes         rooij     paulina         damme
...                 ...          ...           ...         ...           ...
665873          1558810      abraham      schouwen     laurina          hoek
665874          1558811          jan          blok       janna        stelle
665875          1558812  hieronijmus   causmaecker   emerentia  baerdemaeker
665876          1558813     cornelis       sweeden     adriana       lafeber
665877          1558814          jan     landegent     johanna           est
665878          1558815      abraham          veij   barbarina       carlier
665879          1558816     kornelis      ijzerman       maria         beeke
665880          1558817          jan      prooijen    leijntje      kuijpers
665881          1558818      adriaan        spruit   catharina      marcusse
665882          1558819       jannis          back     adriana      hermenet
665883          1558820       pieter     schulling     laurina     dijkgraaf
665884          1558821     arnoldus         jonge  geertruida       oeveren
665885          1558822        jacob       michels    tannetje          neve
665886          1558823     cornelis      zierveld     susanna         smits
665887          1558824       leunis         boven       janna         vinke
665888          1558825          jan        gunter    tannetje       leconte
665889          1558826        jacob          boer       maria         heule
665890          1558827      machiel        korens    cornelia        bruijn
665891          1558828   seraphinus      bunderen     rosalia      janssens
665892          1558829       petrus       vermont      silvia     blommaert
665893          1558830          ivo      mannhart       maria  nachbargauer
665894          1558831
665895          1558832      abraham      hermenet   elizabeth        herman
665896          1558833      michiel       wilhelm     adriana     wilhelmus
665897          1558834      marinus  hollebrandse    tannetje      huijsman
665898          1558835          jan  schilperoort       janna        zoeter
665899          1558836     johannes        bruijn        anna       esbroek
665900          1558837      andries          smit   christina     kriekaert
665901          1558838     cornelis         wisse    jannetje        kunder
665902          1558839       pieter          stee

[665903 rows x 5 columns]

In [4]:
merged.to_csv('datafiles/links/input/overlijden_ouders.csv', header=False, index=False, sep='|', line_terminator='\n')