In [39]:
import os
import sys
import pandas as pd
import numpy as np
import mysql.connector
from string import Template

stdout = sys.stdout
reload(sys)
sys.setdefaultencoding('latin-1')
sys.stdout = stdout

In [8]:
data_path = 'datafiles/links/output/vectortree/'

matches_geboorte = pd.read_csv(data_path + 'matches_links_exact_lvl_3_geboorte.csv', sep='|', index_col=False)
matches_huwelijk = pd.read_csv(data_path + 'matches_links_exact_lvl_3_huwelijk.csv', sep='|', index_col=False)
matches_overlijden = pd.read_csv(data_path + 'matches_links_exact_lvl_3_overlijden.csv', sep='|', index_col=False)

In [10]:
matches_geboorte

,dist,id_1,lname_hw_m,fname_hw_m,lname_hw_f,fname_hw_f,id_2,lname_p_m,fname_p_m,lname_p_f,fname_p_f
0,2,701331,cornelis,jansen,johanna,ee,129230,cornelis,jansen,janna,ee
1,2,701331,cornelis,jansen,johanna,ee,161932,cornelis,jansen,janna,ee
2,0,704975,francois,orlebeke,anna,ee,92863,francois,orlebeke,anna,ee
3,0,704975,francois,orlebeke,anna,ee,347965,francois,orlebeke,anna,ee
4,0,704975,francois,orlebeke,anna,ee,373156,francois,orlebeke,anna,ee
5,0,704975,francois,orlebeke,anna,ee,439624,francois,orlebeke,anna,ee
6,0,704975,francois,orlebeke,anna,ee,480756,francois,orlebeke,anna,ee
7,0,704975,francois,orlebeke,anna,ee,524095,francois,orlebeke,anna,ee
8,2,891300,jannis,verbrugge,johanna,ee,71156,jannis,verbrugge,janna,ee
9,2,891300,jannis,verbrugge,johanna,ee,429783,jannis,verbrugge,janna,ee
10,1,811218,jannis,reu,maria,eggel,296559,jannis,reu,maria,eggee
11,0,726156,jacobus,dieleman,maria,ee,477316,jacobus,dieleman,maria,ee
12,3,847018,jacobus,dieleman,maria,deij,477316,jacobus,dieleman,maria,ee
13,0,871025,pieter,dees,maria,ee,168906,pieter,dees,maria,ee
14,0,871025,pieter,dees,maria,ee,262425,pieter,dees,maria,ee
15,0,871025,pieter,dees,maria,ee,309529,pieter,dees,maria,ee
16,0,871025,pieter,dees,maria,ee,534442,pieter,dees,maria,ee
17,0,871025,pieter,dees,maria,ee,666956,pieter,dees,maria,ee
18,3,820891,johannes,goedhals,adriana,ee,16076,jannis,goedhals,adriana,ee
19,3,820891,johannes,goedhals,adriana,ee,360564,jannis,goedhals,adriana,ee
20,0,820891,johannes,goedhals,adriana,ee,240952,johannes,goedhals,adriana,ee
21,0,762351,cornelis,jonge,sara,ee,406465,cornelis,jonge,sara,ee
22,0,795855,cornelis,kramer,sara,ee,26232,cornelis,kramer,sara,ee
23,0,795855,cornelis,kramer,sara,ee,448142,cornelis,kramer,sara,ee
24,0,795855,cornelis,kramer,sara,ee,520462,cornelis,kramer,sara,ee
25,0,795855,cornelis,kramer,sara,ee,576198,cornelis,kramer,sara,ee
26,0,721357,josephus,babijn,catharina,ee,18791,josephus,babijn,catharina,ee
27,0,721357,josephus,babijn,catharina,ee,76833,josephus,babijn,catharina,ee
28,0,721357,josephus,babijn,catharina,ee,132027,josephus,babijn,catharina,ee
29,0,721357,josephus,babijn,catharina,ee,144839,josephus,babijn,catharina,ee
...,...,...,...,...,...,...,...,...,...,...,...
556519,2,837742,petrus,zegers,thomassina,cornelis,74287,petrus,zeegers,thomasina,cornelis
556520,0,837742,petrus,zegers,thomassina,cornelis,127740,petrus,zegers,thomassina,cornelis
556521,1,837742,petrus,zegers,thomassina,cornelis,257756,petrus,zeegers,thomassina,cornelis
556522,2,837742,petrus,zegers,thomassina,cornelis,306534,petrus,zeegers,thomasina,cornelis
556523,1,837742,petrus,zegers,thomassina,cornelis,319431,petrus,zeegers,thomassina,cornelis
556524,2,837742,petrus,zegers,thomassina,cornelis,323058,petrus,zeegers,thomasina,cornelis
556525,1,837742,petrus,zegers,thomassina,cornelis,365927,petrus,zeegers,thomassina,cornelis
556526,1,837742,petrus,zegers,thomassina,cornelis,384850,petrus,zeegers,thomassina,cornelis
556527,1,837742,petrus,zegers,thomassina,cornelis,625690,petrus,zeegers,thomassina,cornelis
556528,1,837742,petrus,zegers,thomassina,cornelis,688043,petrus,zeegers,thomassina,cornelis
556529,0,821900,cornelis,verbrugge,catholina,krijgsman,92293,cornelis,verbrugge,catholina,krijgsman
556530,0,821900,cornelis,verbrugge,catholina,krijgsman,137151,cornelis,verbrugge,catholina,krijgsman
556531,0,821900,cornelis,verbrugge,catholina,krijgsman,568307,cornelis,verbrugge,catholina,krijgsman
556532,0,821900,cornelis,verbrugge,catholina,krijgsman,608444,cornelis,verbrugge,catholina,krijgsman
556533,0,821900,cornelis,verbrugge,catholina,krijgsman,620501,cornelis,verbrugge,catholina,krijgsman
556534,0,836988,marinus,mieras,stoffelina,schouwenaar,2389,marinus,mieras,stoffelina,schouwenaar
556535,0,780773,adriaan,provoost,catholijntje,cornelis,42024,adriaan,provoost,catholijntje,cornelis
556536,0,780773,adriaan,provoost,catholijntje,cornelis,212253,adriaan,provoost,catholijntje,cornelis
556537,0,780773,adriaan,provoost,catholijntje,cornelis,304802,adriaan,provoost,catholijntje,cornelis
556538,0,780773,adriaan,provoost,catholijntje,cornelis,391621,adriaan,provoost,catholijntje,cornelis
556539,0,780773,adriaan,provoost,catholijntje,cornelis,439373,adriaan,provoost,catholijntje,cornelis
556540,0,780773,adriaan,provoost,catholijntje,cornelis,552100,adriaan,provoost,catholijntje,cornelis
556541,0,780773,adriaan,provoost,catholijntje,cornelis,591744,adriaan,provoost,catholijntje,cornelis
556542,0,780773,adriaan,provoost,catholijntje,cornelis,647255,adriaan,provoost,catholijntje,cornelis
556543,0,780773,adriaan,provoost,catholijntje,cornelis,674799,adriaan,provoost,catholijntje,cornelis
556544,0,759046,johannes,bres,stoffelina,schouwenaar,280519,johannes,bres,stoffelina,schouwenaar
556545,0,759046,johannes,bres,stoffelina,schouwenaar,338310,johannes,bres,stoffelina,schouwenaar
556546,0,759046,johannes,bres,stoffelina,schouwenaar,431651,johannes,bres,stoffelina,schouwenaar
556547,0,759046,johannes,bres,stoffelina,schouwenaar,654818,johannes,bres,stoffelina,schouwenaar
556548,0,764233,jan,ridder,francoise,romeijnsen,326881,jan,ridder,francoise,romeijnsen

In [11]:
matches_huwelijk

,dist,id_1,lname_hw_m,fname_hw_m,lname_hw_f,fname_hw_f,id_2,lname_p_m,fname_p_m,lname_p_f,fname_p_f
0,0,704975,francois,orlebeke,anna,ee,825011,francois,orlebeke,anna,ee
1,0,704975,francois,orlebeke,anna,ee,765913,francois,orlebeke,anna,ee
2,0,704975,francois,orlebeke,anna,ee,867673,francois,orlebeke,anna,ee
3,0,704975,francois,orlebeke,anna,ee,871314,francois,orlebeke,anna,ee
4,0,726156,jacobus,dieleman,maria,ee,792357,jacobus,dieleman,maria,ee
5,3,847018,jacobus,dieleman,maria,deij,792357,jacobus,dieleman,maria,ee
6,0,871025,pieter,dees,maria,ee,797450,pieter,dees,maria,ee
7,0,871025,pieter,dees,maria,ee,887689,pieter,dees,maria,ee
8,0,721357,josephus,babijn,catharina,ee,801059,josephus,babijn,catharina,ee
9,0,721357,josephus,babijn,catharina,ee,770988,josephus,babijn,catharina,ee
10,0,721357,josephus,babijn,catharina,ee,825091,josephus,babijn,catharina,ee
11,0,721357,josephus,babijn,catharina,ee,703554,josephus,babijn,catharina,ee
12,0,721357,josephus,babijn,catharina,ee,714215,josephus,babijn,catharina,ee
13,0,810614,johannes,wit,jozina,ee,734439,johannes,wit,jozina,ee
14,3,888495,johannes,wit,jozina,reems,734439,johannes,wit,jozina,ee
15,0,875766,johannes,pierik,maria,hal,784373,johannes,pierik,maria,hal
16,0,875766,johannes,pierik,maria,hal,824978,johannes,pierik,maria,hal
17,0,875766,johannes,pierik,maria,hal,839133,johannes,pierik,maria,hal
18,1,796899,jacob,cambier,maria,hal,768477,jakob,cambier,maria,hal
19,1,796899,jacob,cambier,maria,hal,818242,jakob,cambier,maria,hal
20,3,863039,emanuel,smidt,sara,halle,878644,emanuel,smedt,sara,hal
21,2,863039,emanuel,smidt,sara,halle,703536,emanuel,smidt,sara,hal
22,2,863039,emanuel,smidt,sara,halle,718028,emanuel,smidt,sara,hal
23,0,798468,anthonie,guerand,pieternella,hal,769503,anthonie,guerand,pieternella,hal
24,2,798468,anthonie,guerand,pieternella,hal,783475,anthonie,geurand,pieternella,hal
25,0,798468,anthonie,guerand,pieternella,hal,858961,anthonie,guerand,pieternella,hal
26,0,863501,pieter,rock,seraphina,hal,788998,pieter,rock,seraphina,hal
27,0,863501,pieter,rock,seraphina,hal,880397,pieter,rock,seraphina,hal
28,1,784965,klaas,groen,joanna,hall,716567,klaas,groen,johanna,hall
29,1,736193,christiaan,baas,joanna,hall,840623,christiaan,baas,johanna,hall
...,...,...,...,...,...,...,...,...,...,...,...
247464,2,740035,izaak,dubois,elizabeth,cornelis,852399,izaak,bois,elizabeth,cornelis
247465,1,824613,izaak,bois,elisabeth,cornelis,852399,izaak,bois,elizabeth,cornelis
247466,1,827896,aarnout,moens,elizabeth,houterman,853985,aarnoud,moens,elizabeth,houterman
247467,1,827896,aarnout,moens,elizabeth,houterman,847733,aarnoud,moens,elizabeth,houterman
247468,1,827896,aarnout,moens,elizabeth,houterman,810496,arnout,moens,elizabeth,houterman
247469,0,827896,aarnout,moens,elizabeth,houterman,841823,aarnout,moens,elizabeth,houterman
247470,2,827896,aarnout,moens,elizabeth,houterman,712249,arenout,moens,elizabeth,houterman
247471,1,827896,aarnout,moens,elizabeth,houterman,825765,aarenout,moens,elizabeth,houterman
247472,0,740035,izaak,dubois,elizabeth,cornelis,716444,izaak,dubois,elizabeth,cornelis
247473,3,824613,izaak,bois,elisabeth,cornelis,716444,izaak,dubois,elizabeth,cornelis
247474,0,740035,izaak,dubois,elizabeth,cornelis,844152,izaak,dubois,elizabeth,cornelis
247475,3,824613,izaak,bois,elisabeth,cornelis,844152,izaak,dubois,elizabeth,cornelis
247476,0,740035,izaak,dubois,elizabeth,cornelis,855596,izaak,dubois,elizabeth,cornelis
247477,3,824613,izaak,bois,elisabeth,cornelis,855596,izaak,dubois,elizabeth,cornelis
247478,1,837742,petrus,zegers,thomassina,cornelis,727010,petrus,zeegers,thomassina,cornelis
247479,1,837742,petrus,zegers,thomassina,cornelis,729061,petrus,zeegers,thomassina,cornelis
247480,1,837742,petrus,zegers,thomassina,cornelis,748065,petrus,zeegers,thomassina,cornelis
247481,1,837742,petrus,zegers,thomassina,cornelis,757003,petrus,zeegers,thomassina,cornelis
247482,1,837742,petrus,zegers,thomassina,cornelis,871750,petrus,zeegers,thomassina,cornelis
247483,2,837742,petrus,zegers,thomassina,cornelis,729859,petrus,zeegers,thomasina,cornelis
247484,1,837742,petrus,zegers,thomassina,cornelis,769571,petrus,zeegers,thomassina,cornelis
247485,2,837742,petrus,zegers,thomassina,cornelis,878560,petrus,zeegers,thomasina,cornelis
247486,0,821900,cornelis,verbrugge,catholina,krijgsman,716815,cornelis,verbrugge,catholina,krijgsman
247487,1,821900,cornelis,verbrugge,catholina,krijgsman,744443,cornelis,verbrugge,catolina,krijgsman
247488,1,880630,marinus,vrieze,stoffelina,almenkinders,844617,marinus,vrieze,stoffelina,almekinders
247489,0,780773,adriaan,provoost,catholijntje,cornelis,761810,adriaan,provoost,catholijntje,cornelis
247490,0,780773,adriaan,provoost,catholijntje,cornelis,718499,adriaan,provoost,catholijntje,cornelis
247491,0,780773,adriaan,provoost,catholijntje,cornelis,827579,adriaan,provoost,catholijntje,cornelis
247492,0,764233,jan,ridder,francoise,romeijnsen,869196,jan,ridder,francoise,romeijnsen
247493,0,764233,jan,ridder,francoise,romeijnsen,733087,jan,ridder,francoise,romeijnsen

In [12]:
matches_overlijden

,dist,id_1,lname_hw_m,fname_hw_m,lname_hw_f,fname_hw_f,id_2,lname_p_m,fname_p_m,lname_p_f,fname_p_f
0,3,851163,pieter,felius,jakoba,as,1484827,pieter,felius,jacoba,NaN
1,3,746354,cornelis,dijkgraaf,cornelia,as,1295681,kornelis,dijkgraaf,cornelia,NaN
2,2,701331,cornelis,jansen,johanna,ee,1186245,cornelis,jansen,janna,ee
3,0,704975,francois,orlebeke,anna,ee,957618,francois,orlebeke,anna,ee
4,0,704975,francois,orlebeke,anna,ee,1134251,francois,orlebeke,anna,ee
5,0,704975,francois,orlebeke,anna,ee,1245185,francois,orlebeke,anna,ee
6,0,704975,francois,orlebeke,anna,ee,1400681,francois,orlebeke,anna,ee
7,0,704975,francois,orlebeke,anna,ee,1550449,francois,orlebeke,anna,ee
8,2,891300,jannis,verbrugge,johanna,ee,1019294,jannis,verbrugge,janna,ee
9,2,891300,jannis,verbrugge,johanna,ee,1364548,jannis,verbrugge,janna,ee
10,0,871025,pieter,dees,maria,ee,1287228,pieter,dees,maria,ee
11,0,871025,pieter,dees,maria,ee,1376207,pieter,dees,maria,ee
12,0,871025,pieter,dees,maria,ee,1384745,pieter,dees,maria,ee
13,0,871025,pieter,dees,maria,ee,1395334,pieter,dees,maria,ee
14,0,871025,pieter,dees,maria,ee,1538468,pieter,dees,maria,ee
15,3,820891,johannes,goedhals,adriana,ee,895369,jannis,goedhals,adriana,ee
16,3,820891,johannes,goedhals,adriana,ee,1273617,jannis,goedhals,adriana,ee
17,0,820891,johannes,goedhals,adriana,ee,1511012,johannes,goedhals,adriana,ee
18,0,795855,cornelis,kramer,sara,ee,900797,cornelis,kramer,sara,ee
19,0,721357,josephus,babijn,catharina,ee,1132854,josephus,babijn,catharina,ee
20,0,721357,josephus,babijn,catharina,ee,1145263,josephus,babijn,catharina,ee
21,0,721357,josephus,babijn,catharina,ee,1162517,josephus,babijn,catharina,ee
22,0,721357,josephus,babijn,catharina,ee,1197440,josephus,babijn,catharina,ee
23,0,721357,josephus,babijn,catharina,ee,1437537,josephus,babijn,catharina,ee
24,0,721357,josephus,babijn,catharina,ee,1542760,josephus,babijn,catharina,ee
25,0,721357,josephus,babijn,catharina,ee,1551629,josephus,babijn,catharina,ee
26,2,721357,josephus,babijn,catharina,ee,1148410,josephus,bombijn,catharina,ee
27,2,867205,jakob,carlier,jozina,hee,1178938,jacob,carlier,jozina,ee
28,2,867205,jakob,carlier,jozina,hee,1435393,jakob,carlier,josina,ee
29,0,774182,johannes,lippens,maria,hal,1374023,johannes,lippens,maria,hal
...,...,...,...,...,...,...,...,...,...,...,...
394221,2,827896,aarnout,moens,elizabeth,houterman,1368251,arenout,moens,elizabeth,houterman
394222,2,827896,aarnout,moens,elizabeth,houterman,1453463,arenout,moens,elizabeth,houterman
394223,0,740035,izaak,dubois,elizabeth,cornelis,1076050,izaak,dubois,elizabeth,cornelis
394224,3,824613,izaak,bois,elisabeth,cornelis,1076050,izaak,dubois,elizabeth,cornelis
394225,1,837742,petrus,zegers,thomassina,cornelis,926829,petrus,zeegers,thomassina,cornelis
394226,2,837742,petrus,zegers,thomassina,cornelis,1096653,petrus,zeegers,thomasina,cornelis
394227,2,837742,petrus,zegers,thomassina,cornelis,1111428,petrus,zeegers,thomasina,cornelis
394228,2,837742,petrus,zegers,thomassina,cornelis,1171981,petrus,zeegers,thomasina,cornelis
394229,1,837742,petrus,zegers,thomassina,cornelis,1496995,petrus,zeegers,thomassina,cornelis
394230,0,821900,cornelis,verbrugge,catholina,krijgsman,985417,cornelis,verbrugge,catholina,krijgsman
394231,0,821900,cornelis,verbrugge,catholina,krijgsman,1053090,cornelis,verbrugge,catholina,krijgsman
394232,0,821900,cornelis,verbrugge,catholina,krijgsman,1113403,cornelis,verbrugge,catholina,krijgsman
394233,1,821900,cornelis,verbrugge,catholina,krijgsman,1399228,cornelis,verbrugge,catolina,krijgsman
394234,1,880630,marinus,vrieze,stoffelina,almenkinders,1318690,marinus,vrieze,stoffelina,almekinders
394235,0,836988,marinus,mieras,stoffelina,schouwenaar,1233559,marinus,mieras,stoffelina,schouwenaar
394236,0,763315,willem,kok,stoffelina,almekinders,1067539,willem,kok,stoffelina,almekinders
394237,0,763315,willem,kok,stoffelina,almekinders,1512763,willem,kok,stoffelina,almekinders
394238,0,780773,adriaan,provoost,catholijntje,cornelis,895059,adriaan,provoost,catholijntje,cornelis
394239,0,780773,adriaan,provoost,catholijntje,cornelis,1037096,adriaan,provoost,catholijntje,cornelis
394240,0,780773,adriaan,provoost,catholijntje,cornelis,1188754,adriaan,provoost,catholijntje,cornelis
394241,0,780773,adriaan,provoost,catholijntje,cornelis,1197662,adriaan,provoost,catholijntje,cornelis
394242,0,780773,adriaan,provoost,catholijntje,cornelis,1247165,adriaan,provoost,catholijntje,cornelis
394243,0,780773,adriaan,provoost,catholijntje,cornelis,1259850,adriaan,provoost,catholijntje,cornelis
394244,0,780773,adriaan,provoost,catholijntje,cornelis,1344014,adriaan,provoost,catholijntje,cornelis
394245,0,780773,adriaan,provoost,catholijntje,cornelis,1362353,adriaan,provoost,catholijntje,cornelis
394246,0,780773,adriaan,provoost,catholijntje,cornelis,1409283,adriaan,provoost,catholijntje,cornelis
394247,0,780773,adriaan,provoost,catholijntje,cornelis,1481934,adriaan,provoost,catholijntje,cornelis
394248,2,867520,marines,vrie,cornelia,stroosnijder,968132,marinus,vrie,cornelis,stroosnijder
394249,0,764233,jan,ridder,francoise,romeijnsen,1232867,jan,ridder,francoise,romeijnsen
394250,0,782992,bonifacius,jonge van ellemeet,francoise,snouck hurgronje,1128268,bonifacius,jonge van ellemeet,francoise,snouck hurgronje

In [61]:
match_insert_query = Template("INSERT INTO vectortree_results (target_id, candidate_id, threshold, distance, registration_type) VALUES ($target_id, $candidate_id, $threshold, $distance, $registration_type)")

def db_insert_match(cursor, prepared_query, row, threshold, registration_type):
    values = {
        'target_id': int(row['id_1']),
        'candidate_id': int(row['id_2']),
        'threshold': threshold,
        'distance': int(row['dist']),
        'registration_type': registration_type
    }
    cursor.execute(prepared_query.safe_substitute(values))

In [63]:
db_conn = mysql.connector.connect(host='localhost', database='links_zeeland', user='root', password='3016BE_17e')
db_conn.autocommit = False
cursor = db_conn.cursor()
try:
    #matches_geboorte.apply(lambda r: db_insert_match(cursor, match_insert_query, r, 3, 1), axis=1)
    matches_huwelijk.apply(lambda r: db_insert_match(cursor, match_insert_query, r, 3, 2), axis=1)
    matches_overlijden.apply(lambda r: db_insert_match(cursor, match_insert_query, r, 3, 3), axis=1)
    db_conn.commit()
except:
    db_conn.rollback()
db_conn.close()