In [1]:
import os
import sys
import pandas as pd
import numpy as np
import mysql.connector

OUTPUT = False

In [2]:
query_years = """
SELECT 
      target_id
    , candidate_id
    , candidate_registration_type
    , target_day
    , target_month
    , target_year
    , candidate_day
    , candidate_month
    , candidate_year
FROM links_meta_data
"""

query_distance = """
SELECT 
      target_id
    , candidate_id
    , candidate_registration_type
    , target_lat
    , target_lon
    , candidate_lat
    , candidate_lon
FROM links_meta_data
"""
db_conn = mysql.connector.connect(host='localhost', database='links_zeeland', user='root', password='3016BE_17e')
matches_years = pd.read_sql(query_years, db_conn)
matches_distance = pd.read_sql(query_distance, db_conn)
matches_distance

,target_id,candidate_id,candidate_registration_type,target_lat,target_lon,candidate_lat,candidate_lon
0,698558,791895,2,51.3127,3.91314,51.3127,3.91314
1,698559,223482,1,51.3306,4.10415,51.3306,4.10415
2,698559,334134,1,51.3306,4.10415,51.3306,4.10415
3,698559,393954,1,51.3306,4.10415,51.3306,4.10415
4,698559,443443,1,51.3306,4.10415,51.3306,4.10415
5,698559,624202,1,51.3306,4.10415,51.3306,4.10415
6,698559,707023,2,51.3306,4.10415,51.3306,4.10415
7,698559,1072215,3,51.3306,4.10415,51.3306,4.10415
8,698559,1243460,3,51.3306,4.10415,51.3306,4.10415
9,698559,1249793,3,51.3306,4.10415,51.3306,4.10415
10,698559,1354090,3,51.3306,4.10415,51.3306,4.10415
11,698560,202050,1,51.4557,3.57649,51.4557,3.57649
12,698560,285369,1,51.4557,3.57649,51.4557,3.57649
13,698560,438361,1,51.4557,3.57649,51.4557,3.57649
14,698560,529099,1,51.4557,3.57649,51.4557,3.57649
15,698560,537391,1,51.4557,3.57649,51.4557,3.57649
16,698560,596573,1,51.4557,3.57649,51.4557,3.57649
17,698560,752801,2,51.4557,3.57649,51.4557,3.57649
18,698560,789750,2,51.4557,3.57649,51.4557,3.57649
19,698560,828156,2,51.4557,3.57649,51.4557,3.57649
20,698560,853001,2,51.4557,3.57649,51.4557,3.57649
21,698560,1353088,3,51.4557,3.57649,51.4557,3.57649
22,698561,234766,1,51.4018,4.20893,51.4018,4.20893
23,698561,543657,1,51.4018,4.20893,51.4018,4.20893
24,698564,48108,1,51.3804,3.50516,51.3804,3.50516
25,698564,101677,1,51.3804,3.50516,51.3804,3.50516
26,698564,114221,1,51.3804,3.50516,51.3804,3.50516
27,698564,177256,1,51.3804,3.50516,51.3804,3.50516
28,698564,182154,1,51.3804,3.50516,51.3804,3.50516
29,698564,322845,1,51.3804,3.50516,51.3804,3.50516
...,...,...,...,...,...,...,...
1198264,892534,1079644,3,51.7266,3.91045,51.7266,3.91045
1198265,892534,1303217,3,51.7266,3.91045,51.7266,3.91045
1198266,892534,1360884,3,51.7266,3.91045,51.7266,3.91045
1198267,892534,1528540,3,51.7266,3.91045,51.7266,3.91045
1198268,892536,164233,1,51.5021,3.88705,51.5021,3.88705
1198269,892536,267688,1,51.5021,3.88705,51.5021,3.88705
1198270,892536,385988,1,51.5021,3.88705,51.5021,3.88705
1198271,892536,617587,1,51.5021,3.88705,51.5021,3.88705
1198272,892536,661219,1,51.5021,3.88705,51.5021,3.88705
1198273,892536,752509,2,51.5021,3.88705,51.5021,3.88705
1198274,892536,876439,2,51.5021,3.88705,51.5021,3.88705
1198275,892536,1115804,3,51.5021,3.88705,51.5021,3.88705
1198276,892536,1126816,3,51.5021,3.88705,51.5021,3.88705
1198277,892536,1460949,3,51.5021,3.88705,51.5021,3.88705
1198278,892537,170670,1,51.4724,3.81641,51.4724,3.81641
1198279,892537,204982,1,51.4724,3.81641,51.4724,3.81641
1198280,892537,475737,1,51.4724,3.81641,51.4724,3.81641
1198281,892537,551234,1,51.4724,3.81641,51.4724,3.81641
1198282,892537,580524,1,51.4724,3.81641,51.4724,3.81641
1198283,892537,583598,1,51.4724,3.81641,51.4724,3.81641
1198284,892537,728539,2,51.4724,3.81641,51.4724,3.81641
1198285,892537,731383,2,51.4724,3.81641,51.4724,3.81641
1198286,892537,757002,2,51.4724,3.81641,51.4724,3.81641
1198287,892537,757894,2,51.4724,3.81641,51.4724,3.81641
1198288,892537,760413,2,51.4724,3.81641,51.4724,3.81641
1198289,892537,766415,2,51.4724,3.81641,51.4724,3.81641
1198290,892537,856927,2,51.4724,3.81641,51.4724,3.81641
1198291,892537,1102933,3,51.4724,3.81641,51.4724,3.81641
1198292,892537,1347099,3,51.4724,3.81641,51.4724,3.81641
1198293,892537,1464415,3,51.4724,3.81641,51.4724,3.81641

In [3]:
matches_years.candidate_day = matches_years.candidate_day.fillna(99).astype(int)
matches_years.candidate_month = matches_years.candidate_month.fillna(99).astype(int)
matches_years.candidate_year = matches_years.candidate_year.fillna(99).astype(int)
matches_years

,target_id,candidate_id,candidate_registration_type,target_day,target_month,target_year,candidate_day,candidate_month,candidate_year
0,698558,791895,2,9,6,1801,5,5,1838
1,698559,223482,1,24,11,1819,3,6,1823
2,698559,334134,1,24,11,1819,17,5,1825
3,698559,393954,1,24,11,1819,17,11,1820
4,698559,443443,1,24,11,1819,26,3,1832
5,698559,624202,1,24,11,1819,23,6,1839
6,698559,707023,2,24,11,1819,19,10,1861
7,698559,1072215,3,24,11,1819,10,11,1863
8,698559,1243460,3,24,11,1819,17,4,1828
9,698559,1249793,3,24,11,1819,9,4,1867
10,698559,1354090,3,24,11,1819,24,7,1847
11,698560,202050,1,14,5,1897,6,1,1913
12,698560,285369,1,14,5,1897,17,1,1898
13,698560,438361,1,14,5,1897,13,7,1900
14,698560,529099,1,14,5,1897,30,8,1911
15,698560,537391,1,14,5,1897,21,3,1899
16,698560,596573,1,14,5,1897,11,3,1907
17,698560,752801,2,14,5,1897,24,7,1925
18,698560,789750,2,14,5,1897,17,2,1928
19,698560,828156,2,14,5,1897,29,4,1932
20,698560,853001,2,14,5,1897,26,7,1922
21,698560,1353088,3,14,5,1897,21,2,1957
22,698561,234766,1,12,10,1882,23,8,1883
23,698561,543657,1,12,10,1882,7,9,1886
24,698564,48108,1,17,8,1887,11,9,1899
25,698564,101677,1,17,8,1887,9,3,1912
26,698564,114221,1,17,8,1887,10,10,1893
27,698564,177256,1,17,8,1887,4,8,1906
28,698564,182154,1,17,8,1887,9,3,1903
29,698564,322845,1,17,8,1887,18,2,1901
...,...,...,...,...,...,...,...,...,...
1198264,892534,1079644,3,20,5,1868,28,3,1871
1198265,892534,1303217,3,20,5,1868,30,7,1944
1198266,892534,1360884,3,20,5,1868,12,9,1872
1198267,892534,1528540,3,20,5,1868,23,3,1942
1198268,892536,164233,1,19,1,1815,21,5,1817
1198269,892536,267688,1,19,1,1815,16,10,1820
1198270,892536,385988,1,19,1,1815,22,3,1819
1198271,892536,617587,1,19,1,1815,25,2,1822
1198272,892536,661219,1,19,1,1815,8,12,1827
1198273,892536,752509,2,19,1,1815,5,5,1843
1198274,892536,876439,2,19,1,1815,6,9,1838
1198275,892536,1115804,3,19,1,1815,16,10,1830
1198276,892536,1126816,3,19,1,1815,17,1,1903
1198277,892536,1460949,3,19,1,1815,11,8,1880
1198278,892537,170670,1,5,5,1870,26,12,1873
1198279,892537,204982,1,5,5,1870,8,10,1875
1198280,892537,475737,1,5,5,1870,21,9,1881
1198281,892537,551234,1,5,5,1870,15,11,1871
1198282,892537,580524,1,5,5,1870,1,5,1879
1198283,892537,583598,1,5,5,1870,29,1,1877
1198284,892537,728539,2,5,5,1870,6,7,1932
1198285,892537,731383,2,5,5,1870,3,3,1910
1198286,892537,757002,2,5,5,1870,15,6,1899
1198287,892537,757894,2,5,5,1870,15,1,1931
1198288,892537,760413,2,5,5,1870,6,4,1899
1198289,892537,766415,2,5,5,1870,18,8,1904
1198290,892537,856927,2,5,5,1870,15,7,1903
1198291,892537,1102933,3,5,5,1870,20,7,1952
1198292,892537,1347099,3,5,5,1870,2,12,1945
1198293,892537,1464415,3,5,5,1870,8,12,1948

In [4]:
matches_years.to_csv('datafiles/dataframes/vectortree_matches_dates.csv', index=False, line_terminator='\n')
matches_distance.to_csv('datafiles/dataframes/vectortree_matches_distance.csv', index=False, line_terminator='\n')